### ISSUE TITLE
voicevox_coreの利用

### ISSUE THREAD

**Issue by takashiTkg** [murmur-develop/murmur#1]
voicevox_coreを使用してパフォーマンス改善を図る

**Comment by takashiTkg** [comment]
https://github.com/VOICEVOX/voicevox_core/tree/main/example/python
公式がバインディング上げてくれてんじゃんアゼルバイジャン

**Comment by ikasoba** [comment]
バインディングこっちかも？
https://github.com/VOICEVOX/voicevox_core/tree/main/crates/voicevox_core_python_api

**Comment by takashiTkg** [comment]
このissue、自分がやると言っていたけれどあまり進捗が無いので他にやりたい人いればやっていただければと

**Comment by ikasoba** [comment]
暇だしやっちゃおうかな

**Comment by takashiTkg** [comment]
大感謝
