### ISSUE TITLE
メンションを読む際、ユーザーのIDが読まれてしまう

### ISSUE THREAD

**Issue by ikasoba** [murmur-develop/murmur#15]
https://discord.com/developers/docs/reference#message-formatting

**Comment by t1nyb0x** [comment]
## UserID置換案

置換先
- ユーザー名
- 空文字に置換してそもそも読まない

## 結論（？）

ユーザー名に置換した方が、文脈がわかりやすそうなのでユーザー名に置換する

**Comment by t1nyb0x** [comment]
挑戦してみたいので、やってみます

**Comment by t1nyb0x** [comment]
ロールメンションは考慮してないので、別途Issue建てて対応したほうが良いかも・・・。
