### ISSUE TITLE
ローマ字では促音が読まれない

### ISSUE THREAD

**Issue by ikasoba** [murmur-develop/murmur#16]
促音用の辞書が足りないので読まれないようです

Discordにて
> 262144 — 今日 02:33
> この読み上げ促音対応してないんですね

**Comment by arakur** [comment]
修正します．

**Comment by ikasoba** [comment]
イイゾ～やったれ

**Comment by arakur** [comment]
辞書のデータに促音のデータを追加する方法の他に，preprocessor.py でデータを読み込む際に促音のパターンを追加する処理を追加する方法もありそうなので，解決方法については検討が必要かもしれません．
