### ISSUE TITLE
Python フォーマッタの統一

### ISSUE THREAD

**Issue by arakur** [murmur-develop/murmur#18]
余分な diff を減らし円滑に作業を進める目的で，Python ファイルのフォーマッタを統一する必要があるように思います．

**Comment by Shion-Amazuki** [comment]
- フォーマッタの指定
- コーディング規約を作って気がついたところを記載していく
が良いかなと思います。

**Comment by Shion-Amazuki** [comment]
フォーマッタについてはどれを選択するか議論が必要かと思います。
私はPythonのフォーマッタを使ったことがないので詳しくないです。

コーディング規約などは項目ごとに議論、チーム内での合意をとる、周知するプロセスが必要かなと思います。

**Comment by arakur** [comment]
フォーマッタについては，特別カスタマイズしたい要求がなければ Black が妥当なように思います．カスタマイズ性が低い分ルールが厳しくプロジェクト内で統一しやすい点，VSCode などでの導入が平易な点などが理由です．

**Comment by takashiTkg** [comment]
ではBlackで統一でよさそうですね
おそらくVSCodeを使用している人が多そうなので、拡張機能を使用していけばいいかなと思います。
[Black Formatter](https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter)をインストール後、以下の設定を追加すると保存時に自動でフォーマットしてくれます。
```
 "[python]": {
    "editor.defaultFormatter": "ms-python.black-formatter",
    "editor.formatOnSave": true
  },
```

**Comment by t1nyb0x** [comment]
VSCodeの推奨拡張機能且つ、Pythonでのデフォルトフォーマッタに設定するjson用意しますね
https://github.com/murmur-develop/murmur/issues/24
