### ISSUE TITLE
branchの運用について

### ISSUE THREAD

**Issue by takashiTkg** [murmur-develop/murmur#19]
## 問題点
現状mainブランチがあるだけでルールも特に適用されていない。  
## やりたいこと
今後リリースをしていくことを考えると今のうちからdevelopブランチなどを設けたり、特定のブランチに直接pushできないように設定をしたい

**Comment by takashiTkg** [comment]
追加  
issueに対するブランチ名もある程度決めたほうがいいとは思いますが、なにかいい案orベストプラクティスがあれば意見ください

**Comment by Shion-Amazuki** [comment]
Git Flow信者なので参考にならないかもしれませんが、このくらいの規模感であればそれで管理できないかなと思います。

コマンドの補助ツールやVSCodeの補助ツールもあったはずです。

イシュー駆動でやるなら、ブランチ名はイシューのIDなどにすると追いやすいはずです。

帰ったら案まとめてみます。

**Comment by takashiTkg** [comment]
恥ずかしながらgit flowについてちゃんと知らなかったので調べたのですが、とても良さそうですね  
issue駆動でやるのがわかりやすいのかなと個人的には考えています  
参考になるブログを書いている方がいたので貼っておきます  
[Issue駆動開発ノススメ](https://kk-web.link/blog/20221202)

**Comment by CAT5NEKO** [comment]
規模的にFlowだと項目が多すぎるから現段階ではMainとDevともう一つぐらいにしておいた方が一貫性が保てそうな気がします。

**Comment by t1nyb0x** [comment]
GitHub flowみたいなやつ使うのどうだろう？と思ったけど、ちょっと複雑だろうか…

**Comment by takashiTkg** [comment]
ではとりあえずの構成として
- main (リリースブランチ)
- develop (基本はここにマージしていく)
- feature/#issue_number (issueに対応したブランチ)
- その他、随時必要なブランチ

のような感じでいきますか  
基本はissueを作ってから対応するブランチを切って、developにマージしていくようにしていきましょう。  
とりあえずmainには直接pushできないようにはしておきます

**Comment by CAT5NEKO** [comment]
これから不特定多数の方が利用されるかもしれない事を想定するとコミットをMainに直刺ししちゃうのは本当に怖いので、
少なくともここだけは早急に他のブランチに刺さるように弄っておきましょう。

**Comment by takashiTkg** [comment]
とりあえずmainとdevelopは直接pushできないようにしました～

**Comment by takashiTkg** [comment]
今後はdevelopから始めてdevelopに対してmergeしていくようにしましょう
Wikiの方に軽くまとめています  
[ブランチの運用について](https://github.com/murmur-develop/murmur/wiki/%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E3%81%AE%E9%81%8B%E7%94%A8%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)
