### ISSUE TITLE
テンプレートの作成

### ISSUE THREAD

**Issue by t1nyb0x** [murmur-develop/murmur#21]
issueテンプレートや、pull requestテンプレートを作った方が良いかも

**Comment by takashiTkg** [comment]
とりあえずgithubの標準のものを適用しちゃいますね  
また必要に応じて編集していく感じで

**Comment by takashiTkg** [comment]
標準のものを適用しようと思ったのですが、issueフォームなるものを使うのが良さそうなのでこちらでやっていきたいですね  
https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

**Comment by takashiTkg** [comment]
上でissueフォームを使用するか検討しましたが、markdown形式のテンプレートで十分だと判断しました。  
Pull requestのテンプレートは`.github`フォルダに、issueテンプレートはgithub上から追加しています。
