### ISSUE TITLE
一度すべてのファイルにフォーマットを掛ける？

### ISSUE THREAD

**Issue by ikasoba** [murmur-develop/murmur#28]
今の状況だとPRなどでファイルを変更した際フォーマットされていないファイルは保存時にフォーマットが走り、大きく変更が入ってしまうのでレビューがすこし面倒になるんじゃないかと思っています。

> 鹿 — 今日 20:25
> 最初の保存だけバカクソ動くことになると思うので、全ファイルフォーマッタ走らせてコミットかけたほうがPR見るとき楽かもと思った

**Comment by takashiTkg** [comment]
そうだね、一度全部フォーマットしてしまいましょう

**Comment by ikasoba** [comment]
PR作りますね～

**Comment by takashiTkg** [comment]
ありがとう〜
