### ISSUE TITLE
discord上でのコマンドの補完の設定 その他botとしての設定など

### ISSUE THREAD

**Issue by takashiTkg** [murmur-develop/murmur#3]
## やりたいこと
- コマンドの補完
- ヘルプ
- その他botの見た目や名前の設定

**Comment by ikasoba** [comment]
こことか雰囲気の参考になりそうかな
https://qiita.com/Kodai0417/items/3abff9575e132e2955ec

**Comment by takashiTkg** [comment]
参考にやってみるね～

**Comment by takashiTkg** [comment]
本当は別のissueに切り出したほうがいいとは思うのですが、ついでに未使用の変数やimport文などを削除するリファクタリングをしたので一緒にプルリクしちゃいます
